from tkinter import *
root = Tk()
C = Canvas(root, height=800, width=800)
C.create_text(400, 30, text="TCS2425044-AdityaParab-GameProgramming")
a = int(input("Enter x1: "))
b = int(input("Enter y1: "))
c = int(input("Enter x2: "))
d = int(input("Enter y2: "))
C.create_rectangle(a, b, c, d, fill="blue")
x = int(input("Enter translation factor Tx: "))
y = int(input("Enter translation factor Ty: "))
C.create_rectangle(a+x, b+y, c+x, d+y, fill="cyan")
C.pack()
root.mainloop()